package org.vamdc.portal.entity.species;

// Generated 22.03.2012 17:15:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SpeciesIso generated by hbm2java
 */
@Entity
@Table(name = "species_iso", uniqueConstraints = {
		@UniqueConstraint(columnNames = "InChI_explicit"),
		@UniqueConstraint(columnNames = "InChIKey_explicit") })
public class SpeciesIso implements java.io.Serializable {

	private static final long serialVersionUID = -1138780756752023000L;

	private Integer id;
	private String inChIExplicit;
	private String inChIkeyExplicit;
	private String inChI;
	private String inChIkey;
	private String conformerStr;
	private int speciesId;
	private String isoName;
	private String isoNameHtml;
	private Double abundance;
	private String afglCode;
	private String cmlExplicit;
	private String cml;
	private String ref;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "InChI_explicit", unique = true, length = 200)
	@Length(max = 200)
	public String getInChIExplicit() {
		return this.inChIExplicit;
	}

	public void setInChIExplicit(String inChIExplicit) {
		this.inChIExplicit = inChIExplicit;
	}

	@Column(name = "InChIKey_explicit", unique = true, length = 27)
	@Length(max = 27)
	public String getInChIkeyExplicit() {
		return this.inChIkeyExplicit;
	}

	public void setInChIkeyExplicit(String inChIkeyExplicit) {
		this.inChIkeyExplicit = inChIkeyExplicit;
	}

	@Column(name = "InChI", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getInChI() {
		return this.inChI;
	}

	public void setInChI(String inChI) {
		this.inChI = inChI;
	}

	@Column(name = "InChIKey", nullable = false, length = 27)
	@NotNull
	@Length(max = 27)
	public String getInChIkey() {
		return this.inChIkey;
	}

	public void setInChIkey(String inChIkey) {
		this.inChIkey = inChIkey;
	}

	@Column(name = "conformer_str", length = 10)
	@Length(max = 10)
	public String getConformerStr() {
		return this.conformerStr;
	}

	public void setConformerStr(String conformerStr) {
		this.conformerStr = conformerStr;
	}

	@Column(name = "species_id", nullable = false)
	public int getSpeciesId() {
		return this.speciesId;
	}

	public void setSpeciesId(int speciesId) {
		this.speciesId = speciesId;
	}

	@Column(name = "iso_name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getIsoName() {
		return this.isoName;
	}

	public void setIsoName(String isoName) {
		this.isoName = isoName;
	}

	@Column(name = "iso_name_html", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getIsoNameHtml() {
		return this.isoNameHtml;
	}

	public void setIsoNameHtml(String isoNameHtml) {
		this.isoNameHtml = isoNameHtml;
	}

	@Column(name = "abundance", precision = 22, scale = 0)
	public Double getAbundance() {
		return this.abundance;
	}

	public void setAbundance(Double abundance) {
		this.abundance = abundance;
	}

	@Column(name = "afgl_code", length = 10)
	@Length(max = 10)
	public String getAfglCode() {
		return this.afglCode;
	}

	public void setAfglCode(String afglCode) {
		this.afglCode = afglCode;
	}

	@Column(name = "cml_explicit")
	public String getCmlExplicit() {
		return this.cmlExplicit;
	}

	public void setCmlExplicit(String cmlExplicit) {
		this.cmlExplicit = cmlExplicit;
	}

	@Column(name = "cml")
	public String getCml() {
		return this.cml;
	}

	public void setCml(String cml) {
		this.cml = cml;
	}

	@Column(name = "ref", length = 10)
	@Length(max = 10)
	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

}
