package org.vamdc.portal.entity.species;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SpeciesSpecies generated by hbm2java
 */
@Entity
@Table(name = "species_species")
public class SpeciesSpecies implements java.io.Serializable {

	private static final long serialVersionUID = 5037197085171323508L;
	private Integer id;
	private String inChI;
	private String inChIkey;
	private String conformerStr;
	private String stoichiometricFormula;
	private int charge;
	private String ordinaryFormula;
	private String ordinaryFormulaHtml;
	private String commonName;
	private String cml;
	private String ref;

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "InChI", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getInChI() {
		return this.inChI;
	}

	public void setInChI(String inChI) {
		this.inChI = inChI;
	}

	@Column(name = "InChIKey", nullable = false, length = 27)
	@NotNull
	@Length(max = 27)
	public String getInChIkey() {
		return this.inChIkey;
	}

	public void setInChIkey(String inChIkey) {
		this.inChIkey = inChIkey;
	}

	@Column(name = "conformer_str", length = 10)
	@Length(max = 10)
	public String getConformerStr() {
		return this.conformerStr;
	}

	public void setConformerStr(String conformerStr) {
		this.conformerStr = conformerStr;
	}

	@Column(name = "stoichiometric_formula", nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getStoichiometricFormula() {
		return this.stoichiometricFormula;
	}

	public void setStoichiometricFormula(String stoichiometricFormula) {
		this.stoichiometricFormula = stoichiometricFormula;
	}

	@Column(name = "charge", nullable = false)
	public int getCharge() {
		return this.charge;
	}

	public void setCharge(int charge) {
		this.charge = charge;
	}

	@Column(name = "ordinary_formula", nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getOrdinaryFormula() {
		return this.ordinaryFormula;
	}

	public void setOrdinaryFormula(String ordinaryFormula) {
		this.ordinaryFormula = ordinaryFormula;
	}

	@Column(name = "ordinary_formula_html", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getOrdinaryFormulaHtml() {
		return this.ordinaryFormulaHtml;
	}

	public void setOrdinaryFormulaHtml(String ordinaryFormulaHtml) {
		this.ordinaryFormulaHtml = ordinaryFormulaHtml;
	}

	@Column(name = "common_name", length = 100)
	@Length(max = 100)
	public String getCommonName() {
		return this.commonName;
	}

	public void setCommonName(String commonName) {
		this.commonName = commonName;
	}

	@Column(name = "cml")
	public String getCml() {
		return this.cml;
	}

	public void setCml(String cml) {
		this.cml = cml;
	}

	@Column(name = "ref", length = 10)
	@Length(max = 10)
	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

}
