package org.vamdc.portal.entity.species;

// Generated 18.09.2012 16:57:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * VamdcMemberDatabaseIdentifiers generated by hbm2java
 */
@Entity
@Table(name = "vamdc_node_species", catalog = "vamdc_species_dev", uniqueConstraints = @UniqueConstraint(columnNames = {
		"species_id", "database_species_id", "member_database_id" }))
public class VamdcMemberDatabaseIdentifiers implements java.io.Serializable {

	private Integer id;
	private VamdcSpecies vamdcSpecies;
	private VamdcMemberDatabases vamdcMemberDatabases;
	private String databaseSpeciesId;

	public VamdcMemberDatabaseIdentifiers() {
	}

	public VamdcMemberDatabaseIdentifiers(VamdcSpecies vamdcSpecies,
			VamdcMemberDatabases vamdcMemberDatabases, String databaseSpeciesId) {
		this.vamdcSpecies = vamdcSpecies;
		this.vamdcMemberDatabases = vamdcMemberDatabases;
		this.databaseSpeciesId = databaseSpeciesId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "species_id", nullable = false)
	@NotNull
	public VamdcSpecies getVamdcSpecies() {
		return this.vamdcSpecies;
	}

	public void setVamdcSpecies(VamdcSpecies vamdcSpecies) {
		this.vamdcSpecies = vamdcSpecies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_database_id", nullable = false)
	@NotNull
	public VamdcMemberDatabases getVamdcMemberDatabases() {
		return this.vamdcMemberDatabases;
	}

	public void setVamdcMemberDatabases(
			VamdcMemberDatabases vamdcMemberDatabases) {
		this.vamdcMemberDatabases = vamdcMemberDatabases;
	}

	@Column(name = "database_species_id", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDatabaseSpeciesId() {
		return this.databaseSpeciesId;
	}

	public void setDatabaseSpeciesId(String databaseSpeciesId) {
		this.databaseSpeciesId = databaseSpeciesId;
	}

}
