package org.vamdc.portal.entity.species;

// Generated 18.09.2012 16:57:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * VamdcSpeciesTypes generated by hbm2java
 */
@Entity
@Table(name = "vamdc_species_types", catalog = "vamdc_species")
public class VamdcSpeciesTypes implements java.io.Serializable {

	private int id;
	private String name;

	public VamdcSpeciesTypes() {
	}

	public VamdcSpeciesTypes(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
