package org.vamdc.portal.entity.species;

// Generated 18.09.2012 16:57:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * VamdcSpeciesNames generated by hbm2java
 */
@Entity
@Table(name = "vamdc_species_names", catalog = "vamdc_species_dev", uniqueConstraints = @UniqueConstraint(columnNames = {
		"species_id", "name", "markup_type_id" }))
public class VamdcSpeciesNames implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3162094765495447143L;
	private Integer id;
	private VamdcSpecies vamdcSpecies;
	private VamdcMarkupTypes vamdcMarkupTypes;
	private String name;
	private int searchPriority;
	private Date created;

	public VamdcSpeciesNames() {
	}

	public VamdcSpeciesNames(VamdcSpecies vamdcSpecies,
			VamdcMarkupTypes vamdcMarkupTypes, String name, int searchPriority,
			Date created) {
		this.vamdcSpecies = vamdcSpecies;
		this.vamdcMarkupTypes = vamdcMarkupTypes;
		this.name = name;
		this.searchPriority = searchPriority;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "species_id", nullable = false)
	@NotNull
	public VamdcSpecies getVamdcSpecies() {
		return this.vamdcSpecies;
	}

	public void setVamdcSpecies(VamdcSpecies vamdcSpecies) {
		this.vamdcSpecies = vamdcSpecies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "markup_type_id", nullable = false)
	@NotNull
	public VamdcMarkupTypes getVamdcMarkupTypes() {
		return this.vamdcMarkupTypes;
	}

	public void setVamdcMarkupTypes(VamdcMarkupTypes vamdcMarkupTypes) {
		this.vamdcMarkupTypes = vamdcMarkupTypes;
	}

	@Column(name = "name", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "search_priority", nullable = false)
	public int getSearchPriority() {
		return this.searchPriority;
	}

	public void setSearchPriority(int searchPriority) {
		this.searchPriority = searchPriority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	@NotNull
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
