package org.vamdc.portal.entity.species;

// Generated 18.09.2012 16:57:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * VamdcSpecies generated by hbm2java
 */
@Entity
@Table(name = "vamdc_species", catalog = "vamdc_species", uniqueConstraints = @UniqueConstraint(columnNames = {
		"inchikey" }))
public class VamdcSpecies implements java.io.Serializable {

	private String id;
	private String inchi;
	private String inchikey;
	private String stoichiometricFormula;
	private int massNumber;
	private int charge;
	private int speciesType;
	private String cml;
	private String mol;
	private String image;
	private String smiles;
	private Date created;
	private int memberDatabasesId;
	private Set<VamdcMemberDatabaseIdentifiers> vamdcMemberDatabaseIdentifierses = new HashSet<VamdcMemberDatabaseIdentifiers>(
			0);
	private Set<VamdcInchikeyExceptions> vamdcInchikeyExceptionses = new HashSet<VamdcInchikeyExceptions>(
			0);
	private Set<VamdcSpeciesStructFormulae> vamdcSpeciesStructFormulaes = new HashSet<VamdcSpeciesStructFormulae>(
			0);
	/*private Set<VamdcSpeciesResources> vamdcSpeciesResourceses = new HashSet<VamdcSpeciesResources>(
			0);*/
	/*private Set<VamdcConformers> vamdcConformerses = new HashSet<VamdcConformers>(
			0);*/
	private Set<VamdcSpeciesNames> vamdcSpeciesNameses = new HashSet<VamdcSpeciesNames>(
			0);

	public VamdcSpecies() {
	}

	public VamdcSpecies(String id, String inchi, String inchikey,
			int inchikeyDuplicateCounter, String stoichiometricFormula,
			int massNumber, int charge, int speciesType, Date created,
			int memberDatabasesId) {
		this.id = id;
		this.inchi = inchi;
		this.inchikey = inchikey;
		//this.inchikeyDuplicateCounter = inchikeyDuplicateCounter;
		this.stoichiometricFormula = stoichiometricFormula;
		this.massNumber = massNumber;
		this.charge = charge;
		this.speciesType = speciesType;
		this.created = created;
		this.memberDatabasesId = memberDatabasesId;
	}

	public VamdcSpecies(
			String id,
			String inchi,
			String inchikey,
			int inchikeyDuplicateCounter,
			String stoichiometricFormula,
			int massNumber,
			int charge,
			int speciesType,
			String cml,
			String mol,
			String image,
			String smiles,
			Date created,
			int memberDatabasesId,
			Set<VamdcMemberDatabaseIdentifiers> vamdcMemberDatabaseIdentifierses,
			Set<VamdcInchikeyExceptions> vamdcInchikeyExceptionses,
			Set<VamdcSpeciesStructFormulae> vamdcSpeciesStructFormulaes,
			//Set<VamdcSpeciesResources> vamdcSpeciesResourceses,
			/*Set<VamdcConformers> vamdcConformerses,*/
			Set<VamdcSpeciesNames> vamdcSpeciesNameses) {
		this.id = id;
		this.inchi = inchi;
		this.inchikey = inchikey;
		/*this.inchikeyDuplicateCounter = inchikeyDuplicateCounter;*/
		this.stoichiometricFormula = stoichiometricFormula;
		this.massNumber = massNumber;
		this.charge = charge;
		this.speciesType = speciesType;
		this.cml = cml;
		this.mol = mol;
		//this.image = image;
		this.smiles = smiles;
		this.created = created;
		this.memberDatabasesId = memberDatabasesId;
		this.vamdcMemberDatabaseIdentifierses = vamdcMemberDatabaseIdentifierses;
		this.vamdcInchikeyExceptionses = vamdcInchikeyExceptionses;
		this.vamdcSpeciesStructFormulaes = vamdcSpeciesStructFormulaes;
		//this.vamdcSpeciesResourceses = vamdcSpeciesResourceses;
		/*this.vamdcConformerses = vamdcConformerses;*/
		this.vamdcSpeciesNameses = vamdcSpeciesNameses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "inchi", nullable = false)
	@NotNull
	public String getInchi() {
		return this.inchi;
	}

	public void setInchi(String inchi) {
		this.inchi = inchi;
	}

	@Column(name = "inchikey", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getInchikey() {
		return this.inchikey;
	}

	public void setInchikey(String inchikey) {
		this.inchikey = inchikey;
	}

	/*@Column(name = "inchikey_duplicate_counter", nullable = false)
	public int getInchikeyDuplicateCounter() {
		return this.inchikeyDuplicateCounter;
	}

	public void setInchikeyDuplicateCounter(int inchikeyDuplicateCounter) {
		this.inchikeyDuplicateCounter = inchikeyDuplicateCounter;
	}*/

	@Column(name = "stoichiometric_formula", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getStoichiometricFormula() {
		return this.stoichiometricFormula;
	}

	public void setStoichiometricFormula(String stoichiometricFormula) {
		this.stoichiometricFormula = stoichiometricFormula;
	}

	@Column(name = "mass_number", nullable = false)
	public int getMassNumber() {
		return this.massNumber;
	}

	public void setMassNumber(int massNumber) {
		this.massNumber = massNumber;
	}

	@Column(name = "charge", nullable = false)
	public int getCharge() {
		return this.charge;
	}

	public void setCharge(int charge) {
		this.charge = charge;
	}

	@Column(name = "species_type_id", nullable = false)
	public int getSpeciesType() {
		return this.speciesType;
	}

	public void setSpeciesType(int speciesType) {
		this.speciesType = speciesType;
	}

	@Column(name = "cml")
	public String getCml() {
		return this.cml;
	}

	public void setCml(String cml) {
		this.cml = cml;
	}

	@Column(name = "mol")
	public String getMol() {
		return this.mol;
	}

	public void setMol(String mol) {
		this.mol = mol;
	}

	@Column(name = "imageURL")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "smiles")
	public String getSmiles() {
		return this.smiles;
	}

	public void setSmiles(String smiles) {
		this.smiles = smiles;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	@NotNull
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "member_databases_id", nullable = false)
	public int getMemberDatabasesId() {
		return this.memberDatabasesId;
	}

	public void setMemberDatabasesId(int memberDatabasesId) {
		this.memberDatabasesId = memberDatabasesId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vamdcSpecies")
	public Set<VamdcMemberDatabaseIdentifiers> getVamdcMemberDatabaseIdentifierses() {
		return this.vamdcMemberDatabaseIdentifierses;
	}

	public void setVamdcMemberDatabaseIdentifierses(
			Set<VamdcMemberDatabaseIdentifiers> vamdcMemberDatabaseIdentifierses) {
		this.vamdcMemberDatabaseIdentifierses = vamdcMemberDatabaseIdentifierses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vamdcSpecies")
	public Set<VamdcInchikeyExceptions> getVamdcInchikeyExceptionses() {
		return this.vamdcInchikeyExceptionses;
	}

	public void setVamdcInchikeyExceptionses(
			Set<VamdcInchikeyExceptions> vamdcInchikeyExceptionses) {
		this.vamdcInchikeyExceptionses = vamdcInchikeyExceptionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vamdcSpecies")
	public Set<VamdcSpeciesStructFormulae> getVamdcSpeciesStructFormulaes() {
		return this.vamdcSpeciesStructFormulaes;
	}

	public void setVamdcSpeciesStructFormulaes(
			Set<VamdcSpeciesStructFormulae> vamdcSpeciesStructFormulaes) {
		this.vamdcSpeciesStructFormulaes = vamdcSpeciesStructFormulaes;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "vamdcSpecies")
	public Set<VamdcSpeciesResources> getVamdcSpeciesResourceses() {
		return this.vamdcSpeciesResourceses;
	}

	public void setVamdcSpeciesResourceses(
			Set<VamdcSpeciesResources> vamdcSpeciesResourceses) {
		this.vamdcSpeciesResourceses = vamdcSpeciesResourceses;
	}*/

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "vamdcSpecies")
	public Set<VamdcConformers> getVamdcConformerses() {
		return this.vamdcConformerses;
	}

	public void setVamdcConformerses(Set<VamdcConformers> vamdcConformerses) {
		this.vamdcConformerses = vamdcConformerses;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vamdcSpecies")
	public Set<VamdcSpeciesNames> getVamdcSpeciesNameses() {
		return this.vamdcSpeciesNameses;
	}

	public void setVamdcSpeciesNameses(
			Set<VamdcSpeciesNames> vamdcSpeciesNameses) {
		this.vamdcSpeciesNameses = vamdcSpeciesNameses;
	}

}
